export const EVENTS = {
  ADMIN_VERIFY_LOGIN: 'ADMIN_VERIFY_LOGIN',
  REGISTER: 'REGISTER',
  VERIFY_LOGIN: 'VERIFY_LOGIN',
  MODIFY_EMAIL: 'MODIFY_EMAIL',
  GENERATE_ADDRESS: 'GENERATE_ADDRESS',
  ENABLE_GAUTH: 'ENABLE_GAUTH',
  DISABLE_GAUTH: 'DISABLE_GAUTH',
  REFERRAL_CODE: 'REFERRAL_CODE',
  LOGOUT: 'LOGOUT',
  CHANGE_USER_STATUS: 'CHANGE_USER_STATUS',
  KYC_APPROVED_LEVEL_1: 'KYC_APPROVED_LEVEL_1',
  KYC_APPROVED_LEVEL_2: 'KYC_APPROVED_LEVEL_2',
  KYC_APPROVED_LEVEL_3: 'KYC_APPROVED_LEVEL_3',
  KYC_REJECTED_LEVEL_1: 'KYC_REJECTED_LEVEL_1',
  SUB_ADMIN_CREATE: 'SUB_ADMIN_CREATE',
  SUB_ADMIN_UPDATE: 'SUB_ADMIN_UPDATE',
  SUB_ADMIN_DELETE: 'SUB_ADMIN_DELETE'
};
 
